site_name: JAGLinux Library
site_url: https://

# Copyright
copyright: Copyright &copy; 2024 JustAGuy Linux

theme:
  name: material
  logo: assets/logo.png
  features:
    - navigation.footer
    - content.code.copy
    - search.suggest
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
