site_name: JustAGuyLinux Library
site_description: Documentation and articles from the JustAGuyLinux YouTube channel and more
site_url: https://justaguylinux.com
     
# Copyright
copyright: Copyright &copy; 2024 JustAGuy Linux

theme:
  name: material
  logo: assets/logo_j.png
  favicon: assets/jaglfav.png
  palette:
    scheme: slate
    primary: custom

  features:
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - search.suggest
    - search.highlight
    - search.share

plugins: 
  - search
  - mkdocs-video:
      is_video: false
      video_muted: false
      video_controls: True
      css_style:
        width: "100%"
        height: 22.172vw;
  - social
  - tags:
      tags_file: tags.md
  - literate-nav:
      nav_file: SUMMARY.md
  - rss:
      abstract_chars_count: 160  # -1 for full content
      abstract_delimiter: <!-- more -->
      categories:
        - tags
      comments_path: "#__comments"
      date_from_meta:
        as_creation: "date" # means from page.meta.date
        as_update: "git" # means from git log
        datetime_format: "%Y-%m-%d %H:%M"
        default_time: "09:30"
        default_timezone: Europe/Paris
      enabled: true
      feed_description: "My custom feed description"  # MkDocs site_description: will be used if this key is not present
      feeds_filenames:
        json_created: feed_json_created.json
        json_updated: feed_json_updated.json
        rss_created: feed_rss_created.xml
        rss_updated: feed_rss_updated.xml
      feed_title: "My custom feed title"  # MkDocs site_name: will be used if this key is not present
      feed_ttl: 1440
      image: https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/128px-Feed-icon.svg.png
      json_feed_enabled: true
      length: 20
      match_path: ".*"
      pretty_print: false
      rss_feed_enabled: true
      url_parameters:
        utm_source: "documentation"
        utm_medium: "RSS"
        utm_campaign: "feed-syndication"
      use_git: true
      use_material_social_cards: true

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/drewgrif
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/justaguylinux
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/justaguylinux
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@justaguylinux
      
extra_css:
  - stylesheets/extra.css
