site_name: JustAGuyLinux Library
site_url: https://mydomain.org/mysite
      
# Copyright
copyright: Copyright &copy; 2024 JustAGuy Linux

theme:
  name: material
  logo: assets/logo.png
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - announce.dismiss
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.tabs.link
    - content.code.annotate
    - header.autohide

plugins: 
  - search
  - social
  - tags:
      tags_file: tags.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/drewgrif
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/justaguylinux
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/justaguylinux
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@justaguylinux
      
extra_css:
  - css/extra.css
